Tag 相关标准完善
zh-blogs/blog-daohang pull request #33
Opened 2024-06-21 11:31 UTC by MYXXTS

#27 #28

2024-06-21 11:37 UTC, MYXXTS commented
process 分支已经建立，可以进行推送和外部合并

2024-06-21 11:38 UTC, linlinzzo requested changes, later dismissed

2024-06-21 11:38 UTC, linlinzzo commented on README.md
> +|   [博客收录](./document/Includ.md)   | 维护组收录的博客说明、自主提交博客收录的说明、对项目收录上游库进行说明 |
```suggestion
|   [博客收录](./document/Include.md)   | 维护组收录的博客说明、自主提交博客收录的说明、对项目收录上游库进行说明 |
```

Typo mistake

2024-06-21 11:59 UTC, aquausora commented on README.md
|                                                       | [Lafcadia](https://github.com/Lafcadia)  |
|                                                       | [aquausora](https://github.com/aquausora)  |

2024-06-21 12:10 UTC, aquausora requested changes

2024-06-21 12:10 UTC, aquausora commented on README.md
> +|                                                       |           [Timozaici](https://github.com/Timozaici)           |
```suggestion
|                                                       |           [Timozaici](https://github.com/Timozaici)           |
|                                                       |           [Kegongteng](https://github.com/gtxykn0504)  |
|                                                       |           [Lafcadia](https://github.com/Lafcadia)              |
|                                                       |           [aquausora](https://github.com/aquausora)       |
```

2024-06-21 12:10 UTC, aquausora commented on document/Tag.md
>  | 文章较少 | 博客文章较少（含有此类Tag的博客文章基本少于十篇） |
```suggestion
| 文章较少 | 博客文章较少（含有此类Tag的博客文章基本少于十篇） |
| 无内容 | 博客无具体内容（如只有一篇初始文章或无文章） |
```

2024-06-21 12:10 UTC, aquausora commented on document/Tag.md
>  |  非原创  |              博客中文章原创内容极少               |
```suggestion
|  非原创  |              博客中文章原创内容极少               |
| 部分内容不宜展示 | 博客中含有依照法律法规要求应当限制展示的内容 |
```

2024-06-21 12:14 UTC, MYXXTS commented
@aquausora clone这个分支写好直接push就行

2024-06-29 12:33 UTC, linlinzzo commented on README.md
> +我们会依据 [项目相关标准](#项目相关标准) 对博客进行 **博客收录**、**信息完善**、**博客分类** 等相关操作，如您发现项目中您博客的信息、分类等内容有误，或者在浏览过程中发现其它博客的信息有误，也欢迎您通过 issue 提出修改意见，我们会尽快处理。
```suggestion
我们会依据 [项目相关标准](#项目相关标准) 对博客进行 **博客收录**、**信息完善**、**博客分类** 等相关操作，如您发现项目中您博客的信息、分类等内容有误，或者在浏览过程中发现其它博客的信息有误，也欢迎您通过 Issue 提出修改意见，我们会尽快处理。
```

2024-06-29 12:33 UTC, linlinzzo commented on README.md
> +我们对项目实行的相关标准和流程（下称 **文档**）放置在当前项目仓库的 [WIKI]() 选项卡中，您可以点击链接前往阅读。
```suggestion
我们对项目实行的相关标准和流程（下称 **文档**）放置在当前项目仓库的 [Wiki](https://github.com/zh-blogs/blog-daohang/wiki) 选项卡中，您可以点击链接前往阅读。
```

2024-06-29 12:33 UTC, linlinzzo commented on README.md
> +## 感谢以下网站对本项目的宣传29   25
```suggestion
## 感谢以下网站对本项目的宣传
```
？

2024-06-30 12:31 UTC, gtxykn0504 reviewed
基本上没有啥问题了。我的留言是一些语言的小优化，不过即使不更改，目前版本也没有大问题

2024-06-30 12:31 UTC, gtxykn0504 commented on .github/ISSUE_TEMPLATE/07-Join Us.yml
“非常感谢您有意加入我们的项目组，并愿意为本项目的发展贡献您的力量。请您按照提供的模板填写申请信息，这将有助于我们更全面地了解您的背景与申请。“

2024-06-30 12:31 UTC, gtxykn0504 commented on .github/ISSUE_TEMPLATE/08-Cooperation Application.yml
感谢您对本项目的支持，同时欢迎您提交合作申请。请您按照以下模板详细填写，以便我们更好地了解您的申请并展开后续的合作事宜。

”欢迎您的合作申请“感觉怪怪的，“欢迎合作申请”？或许”欢迎您提交合作申请“会不会好点

2024-06-30 12:31 UTC, gtxykn0504 commented on CONTRIBUTING.md
对于任何疑问或新标准的提议，我们建议您首先提交一个issue以便我们共同讨论。在提交issue时，您可以按照以下步骤操作，并在相应的issue中附上链接，以便我们更全面地理解和评估您的想法。

2024-06-30 12:31 UTC, gtxykn0504 commented on .github/ISSUE_TEMPLATE/06-Project Proposal.yml
衷心感谢您为本项目提出的宝贵建议，我们将认真评估每一条建议。若您的建议被采纳，我们会在项目中标注您的贡献。请按照以下模板填写您的建议，以便我们快速且全面地了解您的想法。

2024-07-04 04:15 UTC, aquausora commented
#43

2024-07-04 14:46 UTC, aquausora approved these changes

2024-07-06 03:08 UTC, MYXXTS reviewed
大部分文案均已进行重写和修复

2024-07-06 03:11 UTC, aquausora approved these changes

2024-07-06 03:46 UTC, merged